### PR TITLE
Lom 275 seurantasivu print followup

### PR DESCRIPTION
**Pull request by strangeworlder**
# [LOM-275](https://helsinkisolutionoffice.atlassian.net/browse/LOM-275)

## What was done

* There were two new elements added to the submission page. Removed these from the print.
* As the ticket is in review, no need for a new story, just appending the previous merged one.
* Print works now on Firefox.

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout UHF-0000_insert_correct_branch`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Clear caches on your browser. Fire up incognito mode to get the announcements in case you've dismissed them.
* [ ] go to the seurantasivu (login, fill form, click on the right button on kiitossivu)
* [ ] Print the page and see there is no profile block or announcements visible.
* [ ] Check that code follows our standards

## Designers review

* [x] This PR does not need designers review

## Other PRs

[LOM-275]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by jiisuominen — CHANGES_REQUESTED** [review]
Paging seems to be off?
image
image
image

Also profile data list styles as bullets?

**Comment by strangeworlder** [comment]
Made the layout a bit more compact. Also merged the main branch, which made things a lot better for the profile data component.

**Review by jiisuominen — APPROVED** [review]

**Comment by oskarimysteerio** [comment]
List bullet points are gone. The paging is still weird, but I don't remember anymore if we decided to do anything to it 😅 . Otherwise looks good.

**Comment by strangeworlder** [comment]
@oskarimysteerio What browser has strange paging?

**Comment by oskarimysteerio** [comment]
Both FF and Chrome

image

Chrome:

image

**Comment by strangeworlder** [comment]
Interesting. Must be a PC / Mac thing, as mine looks just fine:

Näyttökuva 2023-2-7 kello 11 38 27

**Comment by strangeworlder** [comment]
Will have to continue with PC testing, moving back to draft.

**Comment by strangeworlder** [comment]
@oskarimysteerio can you check on your machine. I tightened things a lot more, but I have a bad feeling it might not work when it hits windows print dialogue.

**Comment by oskarimysteerio** [comment]
@strangeworlder Looks good on PC now

image

**Review by oskarimysteerio — APPROVED** [review]

**Pull request merged**
