### PR TITLE
LOM-355: remove salasanan palautus from login form

### PR DESCRIPTION
**Pull request by suvikankare**
# [LOM-355](https://helsinkisolutionoffice.atlassian.net/browse/LOM-355)

## What was done

* Remove "palauta salasana" from user login form

## How to install

* Make sure your instance is up and running on correct branch.
  * `git checkout LOM-355-salasanan-palautus`
  * `make fresh`
* Run `make drush-cr`

## How to test

* [ ] Go to login form and check that there is no link for changing the password

image

[LOM-355]: https://helsinkisolutionoffice.atlassian.net/browse/LOM-355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by oskarimysteerio** [comment]
Works as advertised, but would check these https://github.com/City-of-Helsinki/drupal-helfi-form-tool/actions/runs/4084461599/jobs/7041186467 code style issues, so the phpcs won't nag us at every commit after this :)

**Review by jiisuominen — APPROVED** [review]
Oskari is right.

**Review by jiisuominen — CHANGES_REQUESTED** [review]
Yeah, PHPCS always before PR.

**Review by jiisuominen — COMMENTED** [review]
YEss. Merged.

**Pull request closed without merging**
